name: Lint Dockerfiles

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - run: brew install hadolint

      - run: |
          hadolint {3.3,3.4,4.0}/**/*Dockerfile
          hadolint {3.3,3.4,4.0}/**/**/*Dockerfile
